### ISSUE TITLE
No provided dependencies for version 1.3.0 and 1.3.1 builds

### ISSUE THREAD

**Issue by 0ffer** [killbill/killbill-client-java#124]
Hi! 
I build app with gradle and killbill client. When we has client version 1.2.6, all transitive dependecies were downloaded successfully.

After upgrade to 1.3.0 something brokes and gradle can't see transitive dependencies.
Also on maven central pages i can see compile dependencies for 1.2.6, but this list is empty for 1.3.0 and 1.3.1
https://mvnrepository.com/artifact/org.kill-bill.billing/killbill-client-java/1.2.6
https://mvnrepository.com/artifact/org.kill-bill.billing/killbill-client-java/1.3.0
https://mvnrepository.com/artifact/org.kill-bill.billing/killbill-client-java/1.3.1

My current solution - just copy needed dependencies in project root dependencies.

In pom within jar all looks good, but i saw that maven shade plugin installed.
If else, then may be wrong jar publicated? (without included dependencies)

**Comment by xsalefter** [comment]
Hi @0ffer , thanks for your report. This issue already addressed and new `killbill-client-java` version has been [published](https://repo1.maven.org/maven2/org/kill-bill/billing/killbill-client-java/1.3.2/). You can give it a try and report new issue if you found the same or any other problems. Meanwhile, I'll close this issue.
