### ISSUE TITLE
Client builds REST URL - 404 Not Found

### ISSUE THREAD

**Issue by akley** [killbill/killbill-client-java#15]
HTTP Client VM option -Dkillbill.url  with "/" as last character provides wrong URL building:
example: http://localhost:8080/ -> http://localhost:8080//1.0/kb/bundles/cecd381d-4dcc-403a-ba93-2fc316b10f58 delivered HTTP 404

Our Kill Bill (0.13.7) is deployed on Tomcat 7.0.47. It seems that Tomcat can not interpret "//" 

Is this possible to fix to make KB more robust on several WebServer containers

**Comment by pierre** [comment]
Couldn't we just make the [parser](https://github.com/killbill/killbill-client-java/blob/master/src/main/java/org/killbill/billing/client/KillBillHttpClient.java#L536) ignore the trailing slash?

**Comment by akley** [comment]
Yeah this line could be the right place in the code to cut off the last character if it is a trailing slash.
