### ISSUE TITLE
HTTP-400 without Response body (client 0.4)

### ISSUE THREAD

**Issue by akley** [killbill/killbill-client-java#16]
Bad Request status is set to server response (in UsageResource.class, method recordUsage) without content. Same in AccountResource.class method createPaymentMethod.

The problem occures if client side deserialized response (deserializeResponse) with status >= 400.
In line 400:
   in = response.getResponseBodyAsStream();
   result = mapper.readValue(in, clazz);

The input stream is empty so the mapper throws while readValue: JsonMappingException: No content to map due to end-of-input 

can you comprehend or confrim this?

Best regards
Alex

**Comment by pierre** [comment]
Is this still happening? If so, could you provide a test to reproduce it?
