### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by awcoding** [killbill/killbill-client-java#2]
At first glance I'm finding the client doesn't have the transactional semantics that I was expecting.
A few questions;
Is Ning using this api?
How does an operator create an external charge?
How do you add taxes and or other charges into an invoice?
Can Kill-Bill handle non-subscription (eg. one off) billing or is that not recommended? If so, can you provide a little bit of code on how to invoice for something and then pay it?

**Comment by krunalpatel1410** [comment]
Hi ,

We want to use subscriptions and payment API   for our java projects .

Can i use killbill-client-java  for communicating with kill bill service?

Krunal

**Comment by pierre** [comment]
@krunalpatel1410 Yes, this is the official Java library to integrate with Kill Bill.

Please use the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead for implementation question.
