### ISSUE TITLE
$03 Forbidden error.

### ISSUE THREAD

**Issue by ManjunathGMN** [killbill/killbill-client-java#75]
Hi team,
I am calling these method and also i am passing requested data to the particular method but getting null value as a response. Is there any thing required to configure in the source code. Please give me guild lines.

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead for implementation questions. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
